# 服务配置（每个单独的服务都需要配置对应的端口）

serve:
  port: 3000
  prefix: /api

# 数据库配置

db:
  type: mysql
  host: localhost
  port: 4407
  username: root
  password: 123456
  database: comic_db
  synchronize: true # 自动同步表

# 缓存配置

cache:
  redis: # 有值时，使用 redis 做缓存服务器
    host:
    port:

# Swagger 配置

# swagger:
#   title: 接口文档
#   description: code:状态码，message:提示信息，data:返回值
#   path: swagger

# 日志存放目录

logsPath: apps
