# 微服务配置

# 微服务 transport 常量

# TCP = 0,
# REDIS = 1,
# NATS = 2,
# MQTT = 3,
# GRPC = 4,
# RMQ = 5,
# KAFKA = 6

# 微服务-服务端配置

microserviceService:
  transport: 0
  options:
    host: 0.0.0.0
    port: 3100
